version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./flags/html:/var/www/html
      - ./flags/app:/var/www/app
      - ./flags/src:/var/www/src
      - ./flags/templates:/var/www/templates
      - ./flags/wikipedia-iso-country-codes.csv:/var/www/wikipedia-iso-country-codes.csv
      - ./data/tmp:/tmp
    logging:
      options:
        max-size: "10k"
    ports:
      - "8000:80"
